import {
    Auction,
    CategoryItem,
    User,
    BidItem,
    WonAuctionItem,
    RatingItem,
    AuctionItem,
    CompletedAuctionItem,
} from '@/types';

export const mockAuctions: Auction[] = [
    {
        id: '1',
        product: {
            id: 'p1',
            name: '14 kt. Yellow gold Aquamarine - Diamond',
            image: '/sample.png',
            category: 'Ring',
            material: 'Diamond',
            brand: 'Luxury Brand',
            description: 'This is a long description of this products',
            specifications: {
                year: '2001',
                totalCaratWeightMainStone: '1.7',
                fineness: '14 K.T',
                totalCaratWeightSurroundingStones: '1.7',
                size: '54 (EU) / 14 (IT) / 6 ¾ (US)',
                totalWeight: '1.7',
                clarity: 'NO',
                origin: 'NEW',
                condition: 'NEW',
            },
        },
        startBid: 10000000,
        currentBid: 12000000,
        bidIncrement: 100000,
        buyNowPrice: 20000000,
        bidCount: 12,
        likeCount: 28,
        isLiked: false,
        startDate: new Date('2025-03-01'),
        endDate: new Date('2025-12-14'),
        status: 'active',
        seller: {
            id: 'seller1',
            username: 'DangKhoa',
            avatar: '/avatars/seller1.jpg',
            tags: 'Verified Seller / Top Rate Seller',
            objectsSold: 4029,
            rating: 4.8,
            reviewCount: 12,
        },
        bids: [
            {
                id: 'bid1',
                amount: 12000000,
                bidder: {
                    id: 'bidder1',
                    username: 'Bidder',
                    avatar: '/avatars/bidder1.jpg',
                    rating: 4.2,
                    reviewCount: 8,
                },
                timestamp: new Date('2025-12-05T10:43:00'),
            },
            {
                id: 'bid2',
                amount: 11500000,
                bidder: {
                    id: 'bidder2',
                    username: 'AuctionUser',
                    avatar: '/avatars/bidder2.jpg',
                    rating: 4.7,
                    reviewCount: 15,
                },
                timestamp: new Date('2025-12-05T09:30:00'),
            },
            {
                id: 'bid3',
                amount: 11000000,
                bidder: {
                    id: 'bidder3',
                    username: 'CollectorX',
                    avatar: '/avatars/bidder3.jpg',
                    rating: 4.9,
                    reviewCount: 22,
                },
                timestamp: new Date('2025-12-05T08:15:00'),
            },
            {
                id: 'bid4',
                amount: 10500000,
                bidder: {
                    id: 'bidder4',
                    username: 'GoldLover',
                    avatar: '/avatars/bidder4.jpg',
                    rating: 4.3,
                    reviewCount: 12,
                },
                timestamp: new Date('2025-12-04T16:22:00'),
            },
            {
                id: 'bid5',
                amount: 10000000,
                bidder: {
                    id: 'bidder5',
                    username: 'StartBidder',
                    avatar: '/avatars/bidder5.jpg',
                    rating: 4.1,
                    reviewCount: 5,
                },
                timestamp: new Date('2025-12-04T10:00:00'),
            },
            {
                id: 'bid6',
                amount: 9500000,
                bidder: {
                    id: 'bidder6',
                    username: 'NewBidder',
                    avatar: '/avatars/bidder6.jpg',
                    rating: 3.8,
                    reviewCount: 3,
                },
                timestamp: new Date('2025-12-04T09:00:00'),
            },
        ],
        qaComments: [
            {
                id: 'qa1',
                author: {
                    id: 'user1',
                    username: 'Ralph Edwards',
                    avatar: '/avatars/user2.jpg',
                    role: 'bidder',
                },
                content:
                    'In mauris porttitor tincidunt mauris massa sit lorem sed scelerisque. Fringilla pharetra vel massa enim sollicitudin cras. At pulvinar eget sociis adipiscing eget donec ultricies nibh tristique.',
                timestamp: new Date('2021-08-18T10:30:00'),
            },
            {
                id: 'qa2',
                author: {
                    id: 'user2',
                    username: 'Jane Cooper',
                    avatar: '/avatars/user3.jpg',
                    role: 'bidder',
                },
                content:
                    "Could you provide more details about the certification and origin of this piece? I'm particularly interested in the gemstone quality.",
                timestamp: new Date('2021-08-19T14:20:00'),
            },
            {
                id: 'qa3',
                author: {
                    id: 'user3',
                    username: 'Michael Chen',
                    avatar: '/avatars/user4.jpg',
                    role: 'bidder',
                },
                content:
                    'Beautiful piece! What is the condition of the setting? Any visible wear or damage?',
                timestamp: new Date('2021-08-20T09:15:00'),
            },
            {
                id: 'qa4',
                author: {
                    id: 'user4',
                    username: 'Sarah Wilson',
                    avatar: '/avatars/user5.jpg',
                    role: 'bidder',
                },
                content:
                    'Is this piece suitable for daily wear or more for special occasions?',
                timestamp: new Date('2021-08-21T16:45:00'),
            },
            {
                id: 'qa5',
                author: {
                    id: 'user5',
                    username: 'David Brown',
                    avatar: '/avatars/user6.jpg',
                    role: 'bidder',
                },
                content:
                    'The craftsmanship looks exceptional. Do you have any documentation about the original purchase or history?',
                timestamp: new Date('2021-08-22T11:20:00'),
            },
        ],
    },
    {
        id: '2',
        product: {
            id: 'p2',
            name: 'Diamond Wedding Ring',
            image: '/sample.png',
            category: 'Ring',
            material: 'Gold',
            brand: 'Diamond Co',
            description:
                'Beautiful diamond wedding ring with excellent clarity',
            specifications: {
                year: '2023',
                totalCaratWeightMainStone: '2.0',
                fineness: '18 K.T',
                totalCaratWeightSurroundingStones: '0.5',
                size: '52 (EU) / 12 (IT) / 6 (US)',
                totalWeight: '2.5',
                clarity: 'VS1',
                origin: 'Belgium',
                condition: 'Excellent',
            },
        },
        startBid: 12000000,
        currentBid: 15000000,
        bidIncrement: 150000,
        buyNowPrice: 25000000,
        bidCount: 8,
        likeCount: 15,
        isLiked: false,
        startDate: new Date('2025-03-05'),
        endDate: new Date('2025-03-18'),
        status: 'active',
        seller: {
            id: 'seller2',
            username: 'DiamondDealer',
            avatar: '/avatars/seller2.jpg',
            tags: 'Verified Seller / Diamond Expert',
            objectsSold: 2156,
            rating: 4.9,
            reviewCount: 28,
        },
        bids: [],
    },
    {
        id: '3',
        product: {
            id: 'p3',
            name: 'Vintage Gold Necklace',
            image: '/sample.png',
            category: 'Necklace',
            material: 'Gold',
            brand: 'Vintage Collection',
            description: 'Elegant vintage gold necklace with intricate design',
            specifications: {
                year: '1985',
                totalCaratWeightMainStone: 'N/A',
                fineness: '22 K.T',
                totalCaratWeightSurroundingStones: 'N/A',
                size: '45cm length',
                totalWeight: '25.5',
                clarity: 'N/A',
                origin: 'Italy',
                condition: 'Very Good',
            },
        },
        startBid: 6000000,
        currentBid: 8000000,
        bidIncrement: 80000,
        buyNowPrice: 8500000,
        bidCount: 25,
        likeCount: 35,
        isLiked: false,
        startDate: new Date('2025-03-01'),
        endDate: new Date('2025-03-15'),
        status: 'active',
        seller: {
            id: 'seller3',
            username: 'AntiqueDealer',
            avatar: '/avatars/seller3.jpg',
            tags: 'Verified Seller / Antique Specialist',
            objectsSold: 3421,
            rating: 4.7,
            reviewCount: 45,
        },
        bids: [],
    },
    {
        id: '4',
        product: {
            id: 'p4',
            name: 'Emerald Earrings',
            image: '/sample.png',
            category: 'Earring',
            material: 'Silver',
            brand: 'Emerald Dreams',
            description: '',
        },
        startBid: 4500000,
        currentBid: 6000000,
        bidIncrement: 60000,
        buyNowPrice: 7000000,
        bidCount: 8,
        likeCount: 22,
        isLiked: false,
        startDate: new Date('2025-03-01'),
        endDate: new Date('2025-03-16'),
        status: 'active',
        seller: {
            id: 'seller4',
            username: 'GemCollector',
            avatar: '/avatars/seller4.jpg',
            tags: 'New Seller',
            objectsSold: 89,
            rating: 4.6,
            reviewCount: 8,
        },
        bids: [],
    },
    {
        id: '5',
        product: {
            id: 'p5',
            name: 'Pearl Bracelet',
            image: '/sample.png',
            category: 'Bracelet',
            material: 'Pearl',
            brand: 'Ocean Pearls',
            description: '',
        },
        startBid: 3000000,
        currentBid: 4500000,
        bidIncrement: 45000,
        buyNowPrice: 5000000,
        bidCount: 15,
        likeCount: 18,
        isLiked: true,
        startDate: new Date('2025-03-01'),
        endDate: new Date('2025-03-17'),
        status: 'active',
        seller: {
            id: 'seller5',
            username: 'PearlExpert',
            avatar: '/avatars/seller5.jpg',
            tags: 'Verified Seller / Pearl Specialist',
            objectsSold: 1876,
            rating: 4.8,
            reviewCount: 22,
        },
        bids: [],
    },
    {
        id: '6',
        product: {
            id: 'p6',
            name: 'Sapphire Pendant',
            image: '/sample.png',
            category: 'Pendant',
            material: 'Silver',
            brand: 'Sapphire World',
            description: '',
        },
        startBid: 5500000,
        currentBid: 7000000,
        bidIncrement: 70000,
        buyNowPrice: 7500000,
        bidCount: 10,
        likeCount: 27,
        isLiked: false,
        startDate: new Date('2025-03-01'),
        endDate: new Date('2025-03-18'),
        status: 'active',
        seller: {
            id: 'seller6',
            username: 'BlueGems',
            avatar: '/avatars/seller6.jpg',
            tags: 'Verified Seller / Gemstone Expert',
            objectsSold: 2743,
            rating: 4.9,
            reviewCount: 31,
        },
        bids: [],
    },
    {
        id: '7',
        product: {
            id: 'p7',
            name: 'Luxury Watch',
            image: '/sample.png',
            category: 'Watch',
            material: 'Leather',
            brand: 'Timekeepers',
            description: '',
        },
        startBid: 25000000,
        currentBid: 30000000,
        bidIncrement: 300000,

        buyNowPrice: 32000000,
        bidCount: 5,
        likeCount: 50,
        isLiked: true,
        startDate: new Date('2025-03-01'),
        endDate: new Date('2025-03-19'),
        status: 'active',
        seller: {
            id: 'seller7',
            username: 'WatchLover',
            avatar: '/avatars/seller7.jpg',
            tags: 'Verified Seller / Top Rate Seller / Watch Expert',
            objectsSold: 567,
            rating: 5.0,
            reviewCount: 18,
        },
        bids: [],
    },
];

export const getTopDealsData = () => {
    const endingSoon = [...mockAuctions].sort(
        (a, b) => new Date(a.endDate).getTime() - new Date(b.endDate).getTime(),
    );

    const mostBids = [...mockAuctions].sort((a, b) => b.bidCount - a.bidCount);

    const highestPrice = [...mockAuctions].sort(
        (a, b) => b.currentBid - a.currentBid,
    );

    return {
        endingSoon,
        mostBids,
        highestPrice,
    };
};

export const mockCategories: CategoryItem[] = [
    {
        id: 'ring-category',
        name: 'Ring',
        image: '/rings.png',
    },
    {
        id: 'earring-jewelry',
        name: 'Earring',
        image: '/earings.png',
    },
    {
        id: 'gemstone-collection',
        name: 'Gemstone',
        image: '/gemstones.png',
    },
    {
        id: 'necklace-accessories',
        name: 'Necklace',
        image: '/necklaces.png',
    },
    {
        id: 'watch-timepieces',
        name: 'Watch',
        image: '/watches.png',
    },
    {
        id: 'diamond-precious',
        name: 'Diamond',
        image: '/diamond.png',
    },
];

export const getCategoriesData = () => {
    return mockCategories;
};

export const getAuctionById = (id: string): Auction | null => {
    return mockAuctions.find((auction) => auction.id === id) || null;
};

export const mockUsers: User[] = [
    {
        id: 'user1',
        email: 'admin@jewelbid.com',
        password: 'admin123',
        name: 'Admin User',
        username: 'admin',
        avatar: '/avatars/admin.jpg',
        address: '123 Admin Street, Ho Chi Minh City',
        phone: '+84 123 456 789',
        role: 'admin',
        createdAt: new Date('2024-01-01'),
    },
    {
        id: 'bidder1',
        email: 'bidder@jewelbid.com',
        password: 'bidder123',
        name: 'Nguyen Van Bidder',
        username: 'bidder_user',
        avatar: '/avatars/bidder.jpg',
        address: '456 Bidder Avenue, Ho Chi Minh City',
        phone: '+84 987 654 321',
        role: 'bidder',
        createdAt: new Date('2024-02-15'),
    },
    {
        id: 'seller1',
        email: 'seller@jewelbid.com',
        password: 'seller123',
        name: 'Tran Thi Khoa',
        username: 'DangKhoa',
        avatar: '/avatars/seller1.jpg',
        address: '789 Seller Lane, Hanoi',
        phone: '+84 111 222 333',
        role: 'seller',
        createdAt: new Date('2024-03-20'),
    },
    {
        id: 'user2',
        email: 'user@jewelbid.com',
        password: 'user123',
        name: 'John Doe',
        username: 'johndoe',
        avatar: '/avatars/user2.jpg',
        address: '321 User Road, Da Nang',
        phone: '+84 444 555 666',
        role: 'user',
        createdAt: new Date('2024-04-10'),
    },
    {
        id: 'user3',
        email: 'test@test.com',
        password: 'test123',
        name: 'Test User',
        username: 'testuser',
        avatar: '/avatars/user3.jpg',
        role: 'user',
        createdAt: new Date('2024-05-01'),
    },
];

export const authenticateUser = (
    email: string,
    password: string,
): User | null => {
    const user = mockUsers.find(
        (u) => u.email === email && u.password === password,
    );

    return user || null;
};

export const getUserByEmail = (email: string): User | null => {
    return mockUsers.find((u) => u.email === email) || null;
};

export const emailExists = (email: string): boolean => {
    return mockUsers.some((u) => u.email === email);
};

export const mockBids: BidItem[] = [
    {
        id: 1,
        product: 'Diamond Ring',
        currentBid: '$500',
        yourBid: '$480',
        timeLeft: '2h 30m',
        status: 'Leading',
    },
    {
        id: 2,
        product: 'Diamond Ring',
        currentBid: '$500',
        yourBid: '$480',
        timeLeft: '2h 30m',
        status: 'Leading',
    },
    {
        id: 3,
        product: 'Diamond Ring',
        currentBid: '$500',
        yourBid: '$480',
        timeLeft: '2h 30m',
        status: 'Leading',
    },
    {
        id: 4,
        product: 'Diamond Ring',
        currentBid: '$500',
        yourBid: '$480',
        timeLeft: '2h 30m',
        status: 'Leading',
    },
    {
        id: 5,
        product: 'Diamond Ring',
        currentBid: '$500',
        yourBid: '$480',
        timeLeft: '2h 30m',
        status: 'Leading',
    },
    {
        id: 6,
        product: 'Diamond Ring',
        currentBid: '$500',
        yourBid: '$480',
        timeLeft: '2h 30m',
        status: 'Leading',
    },
    {
        id: 7,
        product: 'Diamond Ring',
        currentBid: '$500',
        yourBid: '$480',
        timeLeft: '2h 30m',
        status: 'Leading',
    },
    {
        id: 8,
        product: 'Diamond Ring',
        currentBid: '$500',
        yourBid: '$480',
        timeLeft: '2h 30m',
        status: 'Leading',
    },
];

export const mockWonAuctions: WonAuctionItem[] = [
    {
        id: 1,
        product: 'Diamond Ring',
        finalPrice: '$500',
        sellerName: 'John Smith',
        sellerAvatar: '/avatars/seller1.jpg',
        dateWon: '2h 30m',
        action: 'Rating Seller',
    },
    {
        id: 2,
        product: 'Diamond Ring',
        finalPrice: '$500',
        sellerName: 'Jane Doe',
        sellerAvatar: '/avatars/seller2.jpg',
        dateWon: '2h 30m',
        action: 'Rating Seller',
    },
    {
        id: 3,
        product: 'Diamond Ring',
        finalPrice: '$500',
        sellerName: 'Mike Johnson',
        sellerAvatar: '/avatars/seller3.jpg',
        dateWon: '2h 30m',
        action: 'Rating Seller',
    },
    {
        id: 4,
        product: 'Diamond Ring',
        finalPrice: '$500',
        sellerName: 'Sarah Wilson',
        sellerAvatar: '/avatars/seller4.jpg',
        dateWon: '2h 30m',
        action: 'Rating Seller',
    },
];

export const mockRatings: RatingItem[] = [
    {
        id: 1,
        sellerName: 'John Smith',
        comment: 'Great seller, fast shipping!',
        avatar: '/avatars/seller1.jpg',
        rating: 5.0,
        totalReviews: 12,
        date: '2 days ago',
    },
    {
        id: 2,
        sellerName: 'Jane Doe',
        comment: 'Great seller, fast shipping!',
        avatar: '/avatars/seller2.jpg',
        rating: 5.0,
        totalReviews: 12,
        date: '1 week ago',
    },
    {
        id: 3,
        sellerName: 'Mike Johnson',
        comment: 'Great seller, fast shipping!',
        avatar: '/avatars/seller3.jpg',
        rating: 5.0,
        totalReviews: 12,
        date: '2 weeks ago',
    },
];

// Mock data for seller dashboard active auctions
export const mockActiveAuctions: AuctionItem[] = [
    {
        id: '1',
        title: 'Diamond Ring',
        image: '/sample.png',
        currentPrice: 500,
        endTime: '2h 15m',
        totalBids: 12,
        status: 'active',
    },
    {
        id: '2',
        title: 'Gold Necklace',
        image: '/sample.png',
        currentPrice: 750,
        endTime: '1h 45m',
        totalBids: 18,
        status: 'active',
    },
    {
        id: '3',
        title: 'Pearl Earrings',
        image: '/sample.png',
        currentPrice: 320,
        endTime: '3h 20m',
        totalBids: 8,
        status: 'active',
    },
    {
        id: '4',
        title: 'Silver Bracelet',
        image: '/sample.png',
        currentPrice: 450,
        endTime: '4h 10m',
        totalBids: 15,
        status: 'active',
    },
    {
        id: '5',
        title: 'Ruby Ring',
        image: '/sample.png',
        currentPrice: 1200,
        endTime: '5h 30m',
        totalBids: 25,
        status: 'active',
    },
    {
        id: '6',
        title: 'Emerald Pendant',
        image: '/sample.png',
        currentPrice: 890,
        endTime: '6h 15m',
        totalBids: 22,
        status: 'active',
    },
];

// Mock data for seller dashboard completed auctions
export const mockCompletedAuctions: CompletedAuctionItem[] = [
    {
        id: '1',
        title: 'Vintage Diamond Ring',
        image: '/sample.png',
        currentPrice: 850,
        finalPrice: 850,
        endTime: '2h 30m',
        totalBids: 12,
        sellerName: 'John Smith',
        sellerAvatar: '/avatars/user1.jpg',
        sellerRating: 4.8,
        dateWon: '2h 30m',
        status: 'completed',
    },
    {
        id: '2',
        title: 'Gold Wedding Band',
        image: '/sample.png',
        currentPrice: 650,
        finalPrice: 650,
        endTime: '1d 15h',
        totalBids: 9,
        sellerName: 'Jane Doe',
        sellerAvatar: '/avatars/user2.jpg',
        sellerRating: 4.9,
        dateWon: '1d 15h',
        status: 'completed',
    },
    {
        id: '3',
        title: 'Pearl Necklace Set',
        image: '/sample.png',
        currentPrice: 1200,
        finalPrice: 1200,
        endTime: '3d 8h',
        totalBids: 18,
        sellerName: 'Mike Johnson',
        sellerAvatar: '/avatars/user3.jpg',
        sellerRating: 4.6,
        dateWon: '3d 8h',
        status: 'completed',
    },
    {
        id: '4',
        title: 'Sapphire Earrings',
        image: '/sample.png',
        currentPrice: 950,
        finalPrice: 950,
        endTime: '1w 2d',
        totalBids: 14,
        sellerName: 'Sarah Wilson',
        sellerAvatar: '/avatars/user4.jpg',
        sellerRating: 5.0,
        dateWon: '1w 2d',
        status: 'completed',
    },
];
